from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Mapping, Protocol, Sequence, runtime_checkable

from .models import AnalyzerContext, IdentityReference


class ExternalCapability(str, Enum):
    PREVIEW_FRAMES = "preview_frames"
    SUBTITLES = "subtitles"
    MEDIA_METADATA = "media_metadata"
    FINGERPRINTS = "fingerprints"
    KNOWN_IDENTITY = "known_identity"


@dataclass(frozen=True)
class ExternalSourceStatus:
    source_key: str
    available: bool
    capabilities: frozenset[ExternalCapability] = frozenset()
    detail: str = ""


@dataclass(frozen=True)
class ExternalMediaRef:
    source_key: str
    item_id: str
    path: str = ""
    media_source_id: str = ""
    provider_ids: Mapping[str, str] = field(default_factory=dict)
    source_signature: str = ""


@dataclass(frozen=True)
class PreviewFrameRef:
    source_key: str
    item_id: str
    timestamp_ms: int
    asset_ref: str
    source_signature: str
    width: int | None = None
    height: int | None = None


@dataclass(frozen=True)
class ExternalSubtitleRef:
    source_key: str
    item_id: str
    asset_ref: str
    source_signature: str
    language: str = "und"
    title: str = ""
    embedded: bool = False


@dataclass(frozen=True)
class ExternalFingerprint:
    source_key: str
    item_id: str
    algorithm: str
    value: str
    source_signature: str


@runtime_checkable
class ExternalAnalysisSource(Protocol):
    """Read-only adapter for analysis already generated by another media system."""

    source_key: str
    version: str

    def status(self) -> ExternalSourceStatus:
        """Report availability and independently usable capabilities."""
        ...

    def resolve_media(self, context: AnalyzerContext) -> ExternalMediaRef | None:
        """Resolve an InfoMancer file to this source without modifying either system."""
        ...

    def preview_frames(self, media: ExternalMediaRef) -> Sequence[PreviewFrameRef]:
        """Enumerate available timestamped preview evidence lazily."""
        ...

    def read_preview(self, frame: PreviewFrameRef) -> bytes:
        """Read one existing preview image without regenerating it."""
        ...

    def subtitles(self, media: ExternalMediaRef) -> Sequence[ExternalSubtitleRef]:
        """Enumerate subtitle evidence already available from the source."""
        ...

    def read_subtitle(self, subtitle: ExternalSubtitleRef) -> bytes:
        """Read one subtitle asset while keeping source auth/layout inside the adapter."""
        ...

    def media_metadata(self, media: ExternalMediaRef) -> Mapping[str, Any]:
        """Return useful read-only metadata already known by the source."""
        ...

    def fingerprints(self, media: ExternalMediaRef) -> Sequence[ExternalFingerprint]:
        """Return existing content fingerprints when the source exposes them."""
        ...

    def known_identity(self, media: ExternalMediaRef) -> IdentityReference | None:
        """Return the source's known media identity when available."""
        ...
