from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Mapping, Protocol, Sequence, runtime_checkable

from .models import AnalyzerContext, IdentityReference


class ExternalAnalysisError(ValueError):
    """Base error for read-only external analysis adapters."""


class ExternalSourceFailure(ExternalAnalysisError):
    """The external source itself could not be queried or trusted."""


class ExternalPreviewUnavailable(ExternalAnalysisError):
    """Optional preview evidence is absent, stale, or unusable for this item."""


class ExternalCapability(str, Enum):
    PREVIEW_FRAMES = "preview_frames"
    SUBTITLES = "subtitles"
    MEDIA_METADATA = "media_metadata"
    FINGERPRINTS = "fingerprints"
    KNOWN_IDENTITY = "known_identity"


@dataclass(frozen=True)
class ExternalSourceStatus:
    source_key: str
    available: bool
    capabilities: frozenset[ExternalCapability] = frozenset()
    detail: str = ""


@dataclass(frozen=True)
class ExternalMediaRef:
    source_key: str
    item_id: str
    path: str = ""
    media_source_id: str = ""
    provider_ids: Mapping[str, str] = field(default_factory=dict)
    source_signature: str = ""


@dataclass(frozen=True)
class PreviewFrameRef:
    source_key: str
    item_id: str
    timestamp_ms: int
    asset_ref: str
    source_signature: str
    width: int | None = None
    height: int | None = None


@dataclass(frozen=True)
class ExternalSubtitleRef:
    source_key: str
    item_id: str
    asset_ref: str
    source_signature: str
    language: str = "und"
    title: str = ""
    embedded: bool = False


@dataclass(frozen=True)
class ExternalFingerprint:
    source_key: str
    item_id: str
    algorithm: str
    value: str
    source_signature: str


@runtime_checkable
class ExternalAnalysisSource(Protocol):
    """Read-only adapter for analysis already generated by another media system."""

    source_key: str
    version: str

    def status(self) -> ExternalSourceStatus:
        """Report availability and independently usable capabilities."""
        ...

    def resolve_media(self, context: AnalyzerContext) -> ExternalMediaRef | None:
        """Resolve an InfoMancer file to this source without modifying either system."""
        ...

    def preview_frames(self, media: ExternalMediaRef) -> Sequence[PreviewFrameRef]:
        """Enumerate available timestamped preview evidence lazily."""
        ...

    def read_preview(self, frame: PreviewFrameRef) -> bytes:
        """Read one existing preview image without regenerating it."""
        ...

    def subtitles(self, media: ExternalMediaRef) -> Sequence[ExternalSubtitleRef]:
        """Enumerate subtitle evidence already available from the source."""
        ...

    def read_subtitle(self, subtitle: ExternalSubtitleRef) -> bytes:
        """Read one subtitle asset while keeping source auth/layout inside the adapter."""
        ...

    def media_metadata(self, media: ExternalMediaRef) -> Mapping[str, Any]:
        """Return useful read-only metadata already known by the source."""
        ...

    def fingerprints(self, media: ExternalMediaRef) -> Sequence[ExternalFingerprint]:
        """Return existing content fingerprints when the source exposes them."""
        ...

    def known_identity(self, media: ExternalMediaRef) -> IdentityReference | None:
        """Return the source's known media identity when available."""
        ...



class ExternalSourceRegistryError(ValueError):
    """Raised when an external analysis source cannot be registered safely."""


class ExternalSourceRegistry:
    """Small source-agnostic registry for optional read-only analysis adapters."""

    def __init__(self, sources: Sequence[ExternalAnalysisSource] = ()) -> None:
        self._sources: dict[str, ExternalAnalysisSource] = {}
        for source in sources:
            self.register(source)

    @staticmethod
    def _key(value: str) -> str:
        key = str(value or "").strip().casefold()
        if not key:
            raise ExternalSourceRegistryError("An external analysis source requires a key.")
        return key

    def register(self, source: ExternalAnalysisSource) -> None:
        if not isinstance(source, ExternalAnalysisSource):
            raise ExternalSourceRegistryError(
                "External analysis sources must satisfy the ExternalAnalysisSource protocol."
            )
        key = self._key(source.source_key)
        if key in self._sources:
            raise ExternalSourceRegistryError(
                f"External analysis source '{key}' is already registered."
            )
        self._sources[key] = source

    def get(self, source_key: str) -> ExternalAnalysisSource | None:
        return self._sources.get(self._key(source_key))

    def require(self, source_key: str) -> ExternalAnalysisSource:
        key = self._key(source_key)
        source = self._sources.get(key)
        if source is None:
            raise ExternalSourceRegistryError(
                f"External analysis source '{key}' is not registered."
            )
        return source

    def statuses(self) -> tuple[ExternalSourceStatus, ...]:
        statuses: list[ExternalSourceStatus] = []
        for key in sorted(self._sources):
            source = self._sources[key]
            try:
                status = source.status()
            except Exception as exc:
                status = ExternalSourceStatus(
                    source_key=key,
                    available=False,
                    detail=f"Status check failed: {exc}",
                )
            statuses.append(status)
        return tuple(statuses)

    def available_for(
        self, capability: ExternalCapability
    ) -> tuple[ExternalAnalysisSource, ...]:
        available: list[ExternalAnalysisSource] = []
        for key in sorted(self._sources):
            source = self._sources[key]
            try:
                status = source.status()
            except Exception:
                continue
            if status.available and capability in status.capabilities:
                available.append(source)
        return tuple(available)

    def keys(self) -> tuple[str, ...]:
        return tuple(sorted(self._sources))
