"""Read-only external media-system adapters for Episode Identity."""

from .jellyfin import (
    JellyfinAdapterError,
    JellyfinTrickplayAsset,
    JellyfinTrickplaySource,
    JellyfinTrickplayVariant,
    crop_trickplay_frame,
    enumerate_preview_frames,
    external_paths_equal,
    fetch_episode_candidates,
    fetch_item,
    fetch_trickplay_tile,
    parse_trickplay_variants,
    read_trickplay_preview,
    resolve_media_ref,
    select_trickplay_variant,
    trickplay_tile_url,
)

__all__ = [
    "JellyfinAdapterError",
    "JellyfinTrickplayAsset",
    "JellyfinTrickplaySource",
    "JellyfinTrickplayVariant",
    "crop_trickplay_frame",
    "enumerate_preview_frames",
    "external_paths_equal",
    "fetch_episode_candidates",
    "fetch_item",
    "fetch_trickplay_tile",
    "parse_trickplay_variants",
    "read_trickplay_preview",
    "resolve_media_ref",
    "select_trickplay_variant",
    "trickplay_tile_url",
]


from .plex import (
    PlexBifError,
    PlexBifSource,
    PlexPreviewUnavailable,
    PlexBifFrameRange,
    PlexBifIndex,
    bif_source_signature,
    detect_plex_metadata_root,
    effective_plex_metadata_root,
    enumerate_bif_preview_frames,
    enumerate_plex_http_preview_frames,
    fetch_plex_bif_image,
    fetch_plex_bif_index,
    fetch_plex_episode_candidates,
    fetch_plex_item,
    fetch_plex_path_candidates,
    normalize_plex_metadata_root,
    parse_bif_index,
    plex_bif_path_for_bundle,
    read_bif_index,
    resolve_plex_media_ref,
)

__all__ += [
    "PlexBifError",
    "PlexBifSource",
    "PlexPreviewUnavailable",
    "PlexBifFrameRange",
    "PlexBifIndex",
    "bif_source_signature",
    "detect_plex_metadata_root",
    "effective_plex_metadata_root",
    "enumerate_bif_preview_frames",
    "enumerate_plex_http_preview_frames",
    "fetch_plex_bif_image",
    "fetch_plex_bif_index",
    "fetch_plex_episode_candidates",
    "fetch_plex_item",
    "fetch_plex_path_candidates",
    "normalize_plex_metadata_root",
    "parse_bif_index",
    "plex_bif_path_for_bundle",
    "read_bif_index",
    "resolve_plex_media_ref",
]
