from pathlib import Path
import runpy

ROOT = Path(__file__).resolve().parents[1]

# Apply the already-reviewed polish transformation, including the AppStream
# normalization wrapper, then reconcile two existing release contracts.
runpy.run_path(str(ROOT / "scripts/apply_today_release_polish_v2.py"), run_name="__main__")

# Keep the Tauri desktop template parameterized. The packaged .desktop file is
# already validated to resolve these values to InfoMancer/infomancer-desktop.
desktop_path = ROOT / "desktop/src-tauri/linux/InfoMancer.desktop.hbs"
desktop = desktop_path.read_text(encoding="utf-8")
desktop = desktop.replace("Name=InfoMancer", "Name={{name}}", 1)
desktop = desktop.replace(
    "Comment=Self-hosted media catalog and library intelligence",
    "Comment={{comment}}",
    1,
)
desktop = desktop.replace("Icon=infomancer-desktop", "Icon={{icon}}", 1)
desktop_path.write_text(desktop, encoding="utf-8")

# Repair the release-candidate regression contract generated by the first pass
# and make it assert both the parameterized template and the resolved package gate.
test_path = ROOT / "tests/test_beta2_release_candidate_polish.py"
test = test_path.read_text(encoding="utf-8")
test = test.replace(
    'self.assertIn("disabled aria-disabled="true"", template)',
    'self.assertIn(\'disabled aria-disabled="true"\', template)',
    1,
)
test = test.replace(
    "        self.assertIn('Name=InfoMancer', desktop)\n        self.assertIn('Icon=infomancer-desktop', desktop)\n        self.assertIn('release details, and installed icon', workflow)",
    "        self.assertIn('Name={{name}}', desktop)\n        self.assertIn('Icon={{icon}}', desktop)\n        self.assertIn(\"grep -q '^Name=InfoMancer$'\", workflow)\n        self.assertIn(\"grep -q '^Icon=infomancer-desktop$'\", workflow)\n        self.assertIn('release details, and installed icon', workflow)",
    1,
)
test_path.write_text(test, encoding="utf-8")

# This is a one-shot release helper. Keep the resulting branch clean.
(ROOT / "scripts/apply_today_release_polish_v3.py").unlink(missing_ok=True)
